---
server:
    install: '1'
    packages: [vim, git, htop, nodejs, npm]
    timezone: UTC
    locale: pt_BR.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: default, ip: 192.168.33.100, memory: '512', sharedfolder: ./src, useVagrantCloud: '1', syncType: nfs }
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-mysql, php5-mongo, php5-memcached]
xdebug:
    install: '1'
composer:
    install: '1'
memcached:
    install_development_headers: true
